ansible/v1/roles/init_pg_instance/tasks/optional_user_db_setup.yml, pg_spot_operator/cli.py, pg_spot_operator/manifests.py
3 new CLI flags --os-extra-packages, --shared-preload-libraries, --extensions and 1 manifest attribute `postgresql.extensions`  to do a pre-create via Ansible, as can't be done later by user if in non-superuser mode.
To enable non core extensions like postgis or timescaledb. By default load pg_stat_statements only.
```
... --admin-is-superuser false --shared-preload-libraries pg_stat_statements,timescaledb --extensions pg_stat_statements,pgstattuple,timescaledb --os-extra-packages postgresql-16-timescaledb,postgresql-16-postgis-3
```
=> Support adding extensions over the CLI

pg_spot_operator/cli.py
The silence could be a bit too scary.
Should not ruin pipe mode usage as logs go to stderr but connstr to stdout
=> Show progress messages still in --connstr-output-only mode

pg_spot_operator/cli.py, pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/cmdb.py, pg_spot_operator/manifests.py, pg_spot_operator/operator.py, pg_spot_operator/util.py
Currently the engine expected and used the default SSH key for Ansible access.  New manifest section as proably need to add all other Ansible connection opts also to support ProxyCommand etc.
The key still cannot be password protected!
```
python3 -m pg_spot_operator --verbose  --region eu-north-1 --instance-name hello1 --storage-type local --storage-min 10 --ssh-private-key ~/.ssh/google_compute_engine
```
=> New flag --ssh-private-key + Ansible manifest section

example_manifests/hello_aws.yaml, pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/manifests.py
One less resource to create + delete and wait on at teardown. Also of not floating (the default) and in --storage-type=local then there will be no resources hanging when one just terminates the instance from the CLI / portal (given engine stopped)
Rename floating_public_ip -> floating_ips
https://github.com/pg-spot-ops/pg-spot-operator/issues/7
=> Don't create a NIC in floating IP mode

pg_spot_operator/cli.py, pg_spot_operator/operator.py, pg_spot_operator/util.py
To make `pip / pipx` usage more user-friendly - as Ansible not bundled to PyPI currently
=> Auto-download ansible setup scripts from GitHub if missing

README.md, docs/README_env_options.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_impl/aws_vm.py
To specify an existing EC2 SSH key pair to access the VM. Other SSH key inputs also still effective
=> New CLI flag: --aws-key-pair-name / PGSO_AWS_KEY_PAIR_NAME

pg_spot_operator/cli.py, pg_spot_operator/manifests.py, pg_spot_operator/operator.py
vm_only mode is useful for speeding up creation testing or when some ad-hoc / non-Postgres setup is wanted on the VM actually
=> A new top level manifest attribute "vm_only" to skip the Postgres setup

README.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_api.py, pg_spot_operator/cloud_impl/aws_cache.py, pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/cloud_impl/cloud_structs.py, pg_spot_operator/cloud_impl/cloud_util.py, pg_spot_operator/cmdb.py, pg_spot_operator/operator.py, requirements-test.txt, requirements.txt, tests/test_aws_spot.py, tests/test_cloud_api.py, tests/test_cloud_util.py
Don't require AWS creds for --check-price mode - a huge usabilty / first impression fix
Can lie a bit as AWS static S3 price files are a bit more stale than boto3 calls but seems almost the same
=> Non auth price check

README.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_api.py, pg_spot_operator/cloud_impl/aws_spot.py
* Plus better CLI input validation, don't require `--storage-min` set when using network / EBS storage
* Allow global --check-price, don't require region to be set
=> Check price improvements - don't bail when one region's price fetching fails

docs/README_env_options.md, example_manifests/hello_aws.yaml, pg_spot_operator/cli.py
Relevant only for network storage. New flags: `--volume-type`, `--volume-iops`, `--volume-throughput`
=> CLI - add flags to set volume type, iops, bandwith

README.md, docs/README_env_options.md, example_manifests/hello_aws.yaml, pg_spot_operator/cli.py, pg_spot_operator/cloud_api.py, pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/cloud_impl/cloud_util.py, pg_spot_operator/manifests.py, pg_spot_operator/operator.py, tests/test_aws_spot.py, tests/test_cloud_util.py
Allows to target certain manufacturers ("a" for AMD, "g" for AWS Graviton, "i" for Intel) or memory ("r") or compute ("c" ) optimized instance types
```
python3 -m pg_spot_operator --ram-min 1 --check-price  --storage-type local --storage-min=10 --region eu-north-1 --instance-family i3 
Resolving HW requirements to actual instance types / prices using --selection-strategy=balanced ...
Instance type selected for region eu-north-1: i3en.large (x86)
python3 -m pg_spot_operator --ram-min 1 --check-price  --storage-type local --storage-min=10 --region eu-north-1 --instance-family '^r'
Resolving HW requirements to actual instance types / prices using --selection-strategy=balanced ...
Instance type selected for region eu-north-1: r6gd.large (arm)
``` …
=> Add option to select / filter suitable instances based on instance type family regex

.github/workflows/main.yml, pg_spot_operator/operator.py
=> CI test / lint on all modern Python versions

pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/cmdb.py, pg_spot_operator/cmdb_impl/sqlite_migrations.py, pg_spot_operator/constants.py, pg_spot_operator/operator.py, tests/test_operator.py
If we have eviction pressure let's not try to immediately create the same instance type again but select next one
Some info on that re-ordering in debug mode:
```
2024-12-05 14:15:33,330 DEBUG MainThread cmdb.py:662 Discovered short lifetime (<300s within last 30min) instance types: [('m7gd.medium', 'eu-north-1c')]
2024-12-05 14:15:33,330 DEBUG MainThread operator.py:630 Reordering resolved instances shortlist to prefer recently NOT evicted instance types. Original shortlist: [('m7gd.medium', 'eu-north-1c'), ('c7gd.large', 'eu-north-1c'), ('m7gd.large', 'eu-north-1c')]
2024-12-05 14:15:33,330 DEBUG MainThread operator.py:672 Reordered shortlist: [('c7gd.large', 'eu-north-1c'), ('m7gd.large', 'eu-north-1c'), ('m7gd.medium', 'eu-north-1c')]
```
=> Better uptime - create previously fast-failed instance types as last resort only

README.md, docs/README_env_options.md, pg_spot_operator/cli.py, pg_spot_operator/cmdb.py, pg_spot_operator/operator.py
Via `--connstr-format ansible`. Document also in README and hint that one could use the operator also for non-Postgres tasks
=> Add an option to get Ansible inventory suitable output in --connstr-output-only mode

docs/README_env_options.md, pg_spot_operator/cli.py, tests/test_util.py
Does a live query to AWS APIs and shows all Spot operator managed instances in specified regions, together with some key attributes
=> New CLI flag: --list-instances

README.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/util.py, requirements-test.txt, requirements.txt, tests/test_util.py
More friendly `--list-instances` output. Now looking like:
```
+---------------+-------------+---------------------+--------------+------+----------+-----------------------+--------+------------------+-----------------+--------------+--------------------+
| Instance name |      AZ     |      InstanceId     | InstanceType | vCPU | $ (Mon.) |        VolumeId       | Uptime | PrivateIpAddress | PublicIpAddress |    VpcId     |  Expiration Date   |
+---------------+-------------+---------------------+--------------+------+----------+-----------------------+--------+------------------+-----------------+--------------+--------------------+
|      ram8     | eu-north-1c | i-0e1ee862ba39795d6 |  r6g.medium  |  1   |   10.7   | vol-09a6615da5bf6022d | 8 days |   172.31.12.4    |  16.170.230.53  | …
```
=> List instances improvements - pricing info + human readable uptime

README.md, docs/README_env_options.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_api.py, pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/cloud_impl/cloud_structs.py, pg_spot_operator/instance_type_selection.py, pg_spot_operator/manifests.py
A new `--persistent-vms` flag to run on normal non-Spot VMs
=> Allow running on persistent VMs

README.md, docs/README_env_options.md, docs/README_integration.md, pg_spot_operator/cli.py, pg_spot_operator/operator.py
Via `--connstr-output-path` or `CONNSTR_OUTPUT_PATH`
=> New integration option: connect string storing into a local engine node file

README.md, docs/README_env_options.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_api.py, pg_spot_operator/cloud_impl/cloud_structs.py, pg_spot_operator/util.py, tests/test_util.py
Via `--list-avg-spot-savings`
```
python3 -m pg_spot_operator --region=eu --list-avg-spot-savings yes
2025-01-07 15:45:40,145 INFO Regions in consideration based on --region='eu' input: ['eu-central-1', 'eu-central-2', 'eu-north-1', 'eu-south-1', 'eu-south-2', 'eu-west-1', 'eu-west-2', 'eu-west-3']
+--------------+-------------------------+------------------+---------------------------+----------------------------+
|    Region    | Avg. Spot EC2 Savings % | Approx. RDS diff | Avg. Eviction Rate % (Mo) | Mean Time to Eviction (Mo) |
+--------------+-------------------------+------------------+---------------------------+----------------------------+
| eu-south-1   |           72.6          |       5.5x       |           10-15%          |             4              |
| eu-south-2   | …
```
=> New flag to show regional spot stats summary

README.md, ansible/v1/group_vars/all/default_manifest.yml, docs/README_common_issues.md, docs/README_env_options.md, example_manifests/hello_aws.yaml, k8s/README_k8s.md, k8s/example_deployment.yaml, k8s/helm/pg-spot-operator/values.yaml, pg_spot_operator/cli.py, pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/cmdb.py, pg_spot_operator/manifests.py, tests/test_cli.py
Revert https://github.com/pg-spot-ops/pg-spot-operator/commit/ba65186336d5ae4bc462c57f5d3e1be92b09995f: Change CLI input flags logic - all boolean flags accepting values now
As quite inconvenient and non-pythonic in practice and given most people will probably go for Docker usage anyways.
Rename `--ip-floating` to `--static-ip-addresses` and `--assign-public-ip` to `--private-ip-only` so that all boolean flags would be false by default
=> Revert boolean cli flag handling + rename 2 flags

ansible/v1/roles/init_pg_instance/defaults/main.yml, ansible/v1/roles/monitoring_setup/files/db-overview.json, ansible/v1/roles/monitoring_setup/files/health-check.json, ansible/v1/roles/monitoring_setup/files/prometheus_default_datasource.yml, ansible/v1/roles/monitoring_setup/files/sessions-overview.json, ansible/v1/roles/monitoring_setup/files/table-details.json, ansible/v1/roles/monitoring_setup/files/tables-top.json, ansible/v1/roles/monitoring_setup/tasks/main.yml, ansible/v1/roles/monitoring_setup/templates/pgwatch.service.j2, ansible/v1/roles/monitoring_setup/templates/pgwatch_sources.yaml.j2, ansible/v1/roles/open_pg_instance_access/templates/pg_hba.conf.j2, pg_spot_operator/cli.py, pg_spot_operator/manifests.py
Install [cybertec-postgresql/pgwatch ](https://github.com/cybertec-postgresql/pgwatch) daemon in Prometheus mode when `--monitoring` set, together with some basic dashboards to monitor `pg_stat*` activity
Closes https://github.com/pg-spot-ops/pg-spot-operator/issues/39
=> Add postgres monitoring via pgwatch

ansible/v1/roles/os_setup/tasks/main.yml, ansible/v1/roles/os_setup/templates/disable-thp.service.j2
As generally negative for databases that manage their own memory
=> Disable Linux Transparent Huge Pages directly after boot

ansible/v1/roles/init_pg_instance/templates/pgspotops.conf.j2, ansible/v1/roles/os_setup/tasks/main.yml, pg_spot_operator/pgtuner.py, pg_spot_operator/util.py, tests/test_util.py
Enable huge pages for larger (>8GB) Shared Bufffers as can bring visible performance improvements
=> Enable huge pages for large ram skus

pg_spot_operator/cloud_impl/aws_cache.py, pg_spot_operator/cloud_impl/aws_vm.py
Cache AMI details per region / cpu arch, as change only about 1x per month and can save some API calls.
```
$ cat .pg-spot-operator/price_cache/aws_ami_eu-north-1_amd64_2025_w8.json
{"PlatformDetails": "Linux/UNIX", "UsageOperation": "RunInstances", "BlockDeviceMappings": [{"Ebs": {"DeleteOnTermination": true, "Iops": 3000, "SnapshotId": "snap-0ab8147bd1888d69e", "VolumeSize": 8, "VolumeType": "gp3", "Throughput": 125, "Encrypted": false}, "DeviceName": "/dev/xvda"}], "Description": "Debian 12 (20250210-2019)", "EnaSupport": true, "Hypervisor": "xen", "ImageOwnerAlias": "amazon", "Name": "debian-12-amd64-20250210-2019", "RootDeviceName": "/dev/xvda", "RootDeviceType": "ebs", "SriovNetSupport": "simple", "VirtualizationType": "hvm", "DeprecationTime": "2027-02-10T17:12:19.000Z", "ImageId": …
```
=> Ami caching

README.md, docs/README_env_options.md, pg_spot_operator/cli.py, pg_spot_operator/constants.py, pg_spot_operator/manifests.py, pg_spot_operator/operator.py
Can get the previous "plain VM" only mode via the `--no-mount-disks` flag. Disks are mounted to /var/lib/postgresql
=> By default mount data disks also in `--vm-only` mode
