README.md
=> proofread readme

pg_spot_operator/cmdb.py, pg_spot_operator/cmdb_impl/sqlite_migrations.py, pg_spot_operator/operator.py
To to counter the "runaway daemon on some other currently unaccessible host" problem
=> Detect externally set expiration tags and terminate the instance if needed

pg_spot_operator/cmdb.py, pg_spot_operator/operator.py
Normally should not happen but possible. Re-register in CMDB then.
=> Survive when public or private primary IP address of instances changes

pg_spot_operator/cmdb.py, pg_spot_operator/operator.py
To be able to quickly check what's going on on the VM
https://github.com/pg-spot-ops/pg-spot-operator/issues/26
=> Show the SSH connect string on VM create / instance setup finished

pg_spot_operator/cloud_api.py, pg_spot_operator/operator.py
Addition to https://github.com/pg-spot-ops/pg-spot-operator/issues/13
=> Some messages were still only about looking for the cheapest VM

pg_spot_operator/operator.py
If there are no volumes (--storage-type=local) then no reason to sleep. And if using floating IPs then NIC is set to DeleteOnTermination and don't have to do anything
=> Faster teardown - don't sleep unnecessarily

pg_spot_operator/cli.py, pg_spot_operator/operator.py
For example when wanting to do some customizations to the Postgres setup or when using via PyPI / pipx
=> Make custom Ansible paths possible via --ansible-path

README.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/manifests.py, pg_spot_operator/operator.py
A new manifest attribute / CLI flag --aws-vpc-id + README update
=> Allow using non-default VPCs

pg_spot_operator/cli.py, pg_spot_operator/operator.py
To lower the likelyhood of leaking any passwords
=> Delete tmp Ansible folder after success

scripts/aws/delete_all_operator_tagged_objects.sh
Go region-by-region + require params explicitly. If none given show usage:
```
Usage: delete_all_operator_tagged_objects.sh  yes/no (DRY RUN MODE)  ['eu-west-1 eu-north-1' OPTIONAL EXPLICIT REGION LIST]
```
=> Refactor cleanup helper

README.md, docs/README_env_options.md
=> Add a separate Readme for CLI options

scripts/terraform/create-iam-user-and-credentials/create_region_limited_user.tf, scripts/terraform/create-vpc/create_vpc.tf
IAM policies are region limited for additional play safety
=> Example Terraform to create a sandbox VPC + IAM user + creds

pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/operator.py
Better ordering of teardown steps + only delete the instance name tagged EIP
=> Teardown fixes

Containerfile
As things seems to have matured enough
https://github.com/pg-spot-ops/pg-spot-operator/issues/74
=> Docker - switch to a non-root image

Containerfile, entrypoint.sh
Add a dump-init entrypoint wrapper for that
=> Docker - generate SSH keys properly during runtime

k8s/helm/pg-spot-operator/.helmignore, k8s/helm/pg-spot-operator/Chart.yaml, k8s/helm/pg-spot-operator/templates/_helpers.tpl, k8s/helm/pg-spot-operator/templates/deployment.yaml, k8s/helm/pg-spot-operator/templates/pv.yaml, k8s/helm/pg-spot-operator/templates/pvc.yaml, k8s/helm/pg-spot-operator/templates/serviceaccount.yaml, k8s/helm/pg-spot-operator/values.yaml
=> K8s - add a minimal Helm chart

pg_spot_operator/cli.py, pg_spot_operator/cloud_api.py, pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/constants.py, pg_spot_operator/operator.py, pg_spot_operator/util.py, tests/test_aws_spot.py, tests/test_util.py
fixes https://github.com/pg-spot-ops/pg-spot-operator/issues/11
=> fetch price info via AWS endpoints

docs/README_env_options.md, pg_spot_operator/cli.py
List regions with city names and exit. Hard-coded into source code, thus needs update time-to-time but should be static enough
=> New CLI flag: --list-regions

README.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_api.py, pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/cloud_impl/cloud_structs.py, pg_spot_operator/cmdb.py, pg_spot_operator/instance_type_selection.py, pg_spot_operator/manifests.py, pg_spot_operator/operator.py, requirements-test.txt, requirements.txt, tests/test_aws_spot.py, tests/test_cli.py, tests/test_instance_selection.py
Try up to 3 instance types during one main loop. Also improve `--check-price` output - now a table.
=> Better HA - try next cheapest SKU when getting InsufficientInstanceCapacity on VM create

pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/operator.py, tests/test_aws_spot.py
Didn't work after an engine restart
=> Spot price displaying of running instances was flawed

docs/README_env_options.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_api.py, pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/instance_type_selection.py, pg_spot_operator/manifests.py, tests/test_instance_selection.py
Plus validation for `--selection-strategy` and make strategies string constants
=> A new CLI flag:  --list-strategies

README.md, docs/README_env_options.md, docs/README_integration.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_impl/aws_s3.py, pg_spot_operator/manifests.py, pg_spot_operator/operator.py, tests/test_aws_s3.py
New flags:
```
--connstr-bucket / CONNSTR_BUCKET (Required for S3 push to work)
--connstr-bucket-key / CONNSTR_BUCKET_KEY (Required for S3 push to work)
--connstr-bucket-region / CONNSTR_BUCKET_REGION
--connstr-bucket-endpoint / CONNSTR_BUCKET_ENDPOINT
--connstr-bucket-access-key / CONNSTR_BUCKET_ACCESS_KEY
--connstr-bucket-access-secret / CONNSTR_BUCKET_ACCESS_SECRET
```
=> New app integration feature -  connect string info pushing to S3

docs/README_env_options.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/manifests.py
Handy to increase ti for on-the-vm experimenting , temp backups etc
=> New HW attribute: --os-disk-size with 20GB default

pg_spot_operator/cloud_impl/aws_vm.py, pg_spot_operator/operator.py
And show a nice error message referencing docs
```
2025-01-02 17:21:50,765 ERROR Max spot instance count exceeded in region eu-north-1 - quota increase required, see docs/README_common_issues.md for more
```
=> Dont retry vm create on Spot vCPU quota breach

docs/README_env_options.md, pg_spot_operator/cli.py, pg_spot_operator/cloud_api.py, pg_spot_operator/cloud_impl/aws_spot.py, pg_spot_operator/manifests.py
Add --max-price flag filtering. In hourly prices.
As per https://github.com/pg-spot-ops/pg-spot-operator/issues/128
=> Max price flag

docs/README_env_options.md, pg_spot_operator/cli.py, pg_spot_operator/cmdb.py, pg_spot_operator/cmdb_impl/sqlite_migrations.py, pg_spot_operator/constants.py, pg_spot_operator/manifests.py, pg_spot_operator/operator.py
Via `--stop` and `--resume`. These two parameters can be used without a `--region` for convenience, unlike most other subcommands
=> Add stop / resume functionality
